In [0]:
import numpy as np
import pandas as pd
from google.colab import drive
from sklearn.metrics import f1_score, make_scorer
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

In [2]:
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
file_loc = '/content/drive/My Drive/Decision_Tree_Example/loan_prediction.csv'

In [0]:
df = pd.read_csv(file_loc)

In [5]:
df.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         0.0             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History  Loan_Status  
0             1.0            1  
1             1.0            0  
2             1.0            1  
3             1.0            1  
4             1.0            1

In [6]:
df.shape

(614, 6)

In [0]:
from sklearn.tree import DecisionTreeClassifier as dt
clf = dt()

In [10]:
clf

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [0]:
X = df.iloc[:,0:len(df.columns)-1].values
Y = df.iloc[:,-1].values

In [16]:
X.shape

(614, 5)

In [19]:
Y.shape

(614,)

In [0]:
X_train,X_test,Y_train,Y_test = train_test_split(X, Y, test_size=0.25, random_state=0)

In [25]:
X_train.shape

(460, 5)

In [27]:
X_test.shape

(154, 5)

In [0]:
a, b = np.arange(10).reshape((5, 2)), range(5)

In [29]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [30]:
b

range(0, 5)

In [0]:
X_train1,X_test1,Y_train1,Y_test1 = train_test_split(a, b)

In [33]:
X_train1

array([[4, 5],
       [6, 7],
       [8, 9]])

In [34]:
Y_train1

[2, 3, 4]

In [0]:
X_train2,X_test2,Y_train2,Y_test2 = train_test_split(a, b)

In [36]:
X_train2

array([[0, 1],
       [4, 5],
       [6, 7]])

In [0]:
X_train3, X_test3,Y_train3,Y_test3 = train_test_split(a, b, random_state = 8)

In [38]:
X_train3

array([[2, 3],
       [0, 1],
       [6, 7]])

In [0]:
X_train4, X_test4,Y_train4,Y_test4 = train_test_split(a, b, random_state = 8)

In [40]:
X_train4

array([[2, 3],
       [0, 1],
       [6, 7]])

In [0]:
# Fit the model
clf.fit(X_train, Y_train)

# Make predictions
train_predictions = clf.predict(X_train)
test_predictions = clf.predict(X_test)

In [45]:
print('The Training F1 Score is', f1_score(train_predictions, Y_train))
print('The Testing F1 Score is', f1_score(test_predictions, Y_test))

The Training F1 Score is 1.0
The Testing F1 Score is 0.7420814479638009


In [0]:
parameters = {'max_depth':[1,2,3,4,5], 'min_samples_leaf':[1,2,3,4,5], 'min_samples_split':[2,3,4,5], 'criterion' : ['gini','entropy']}
scorer = make_scorer(f1_score)

In [0]:
grid_obj = GridSearchCV(clf, parameters, scoring=scorer)

In [52]:
grid_fit = grid_obj.fit(X_train, Y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [0]:
best_clf = grid_fit.best_estimator_

In [54]:
best_clf

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=1,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [55]:
best_clf.fit(X_train, Y_train)

# Make predictions using the new model.
best_train_predictions = best_clf.predict(X_train)
best_test_predictions = best_clf.predict(X_test)

# Calculate the f1_score of the new model.
print('The training F1 Score is', f1_score(best_train_predictions, Y_train))
print('The testing F1 Score is', f1_score(best_test_predictions, Y_test))


The training F1 Score is 0.8360902255639098
The testing F1 Score is 0.8620689655172413
